#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-99}
PGID=${PGID:-100}

groupmod -o -g "${PGID}" abc
usermod -o -u "${PUID}" abc

User UID:    $(id -u abc)
User GID:    $(id -g abc)

lsiown abc:abc /app
